# Generated by Django 2.1.2 on 2018-10-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20181030_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField(null=True)),
                ('ingredients', models.ManyToManyField(to='ingredients.Ingredient')),
            ],
        ),
    ]
